version: "3.3"
services:
  py27_logger:
    build: .
    container_name: py27_logger
    command: gunicorn --bind 0.0.0.0:5000 app.app:app
    restart: always
    labels:
      - traefik.backend=py27_logger
      - traefik.frontend.rule=Host:api.learnet.io
      - traefik.docker.network=traefik_network
      - traefik.port=5000
    ports:
      - "5000:5000"
    environment:
      - EMAIL_USER=learnet.io.user@gmail.com
      - EMAIL_PASSWORD=Moon-age-dream-1970